wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.19.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744545398
    t:
      1:
      - 1
      - 55
      3:
      - 4
      - 13
      - 14
      - 16
      - 23
      - 42
      - 55
      4: 3.12.2
      5: 0.19.8
      8:
      - 3
      - 5
      13: windows-amd64
time_limit:
  desc: null
  value: 100300
checkpoint:
  desc: null
  value: true
resume_run_name:
  desc: null
  value: ''
additional_timesteps:
  desc: null
  value: 10000
alg:
  desc: null
  value: DQN
seed:
  desc: null
  value: 0
verbose:
  desc: null
  value: true
exp_tag:
  desc: null
  value: nhap2
track:
  desc: null
  value: true
wandb_project:
  desc: null
  value: rl2grid_bugfinder
wandb_entity:
  desc: null
  value: ''
wandb_mode:
  desc: null
  value: offline
th_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: false
n_threads:
  desc: null
  value: 4
env_id:
  desc: null
  value: bus14
n_envs:
  desc: null
  value: 10
action_type:
  desc: null
  value: topology
difficulty:
  desc: null
  value: 0
env_config_path:
  desc: null
  value: scenario.json
norm_obs:
  desc: null
  value: true
use_heuristic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 300
learning_starts:
  desc: null
  value: 10000
layers:
  desc: null
  value:
  - 64
  - 64
act_fn:
  desc: null
  value: relu
lr:
  desc: null
  value: 0.00025
train_freq:
  desc: null
  value: 10
gamma:
  desc: null
  value: 0.9
tau:
  desc: null
  value: 1.0
tg_qnet_freq:
  desc: null
  value: 1000
eps_start:
  desc: null
  value: 1.0
eps_end:
  desc: null
  value: 0.05
eps_decay_frac:
  desc: null
  value: 0.4
buffer_size:
  desc: null
  value: 250000
batch_size:
  desc: null
  value: 128
