_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.2
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
act_fn:
    value: relu
action_type:
    value: topology
additional_timesteps:
    value: 100000
alg:
    value: DQN
batch_size:
    value: 128
buffer_size:
    value: 500000
checkpoint:
    value: true
cuda:
    value: true
difficulty:
    value: 0
env_config_path:
    value: scenario.json
env_id:
    value: bus14
eps_decay_frac:
    value: 0.5
eps_end:
    value: 0.05
eps_start:
    value: 1
exp_tag:
    value: ONLINE
gamma:
    value: 0.9
layers:
    value:
        - 64
        - 64
learning_starts:
    value: 20000
lr:
    value: 0.00025
n_envs:
    value: 10
n_threads:
    value: 4
norm_obs:
    value: true
resume_run_name:
    value: ""
seed:
    value: 42
tau:
    value: 1000
tg_qnet_freq:
    value: 1000
th_deterministic:
    value: false
time_limit:
    value: 4000
total_timesteps:
    value: 3000
track:
    value: true
train_freq:
    value: 20
use_heuristic:
    value: true
verbose:
    value: true
wandb_entity:
    value: ""
wandb_mode:
    value: online
wandb_project:
    value: rl2grid_bugfinder
