_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 35
                - 55
            "4": 3.12.2
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
action_type:
    value: redispatch
actor_act_fn:
    value: tanh
actor_layers:
    value:
        - 512
        - 256
        - 256
actor_lr:
    value: 0.00025
additional_timesteps:
    value: 500000
alg:
    value: PPO
anneal_lr:
    value: true
checkpoint:
    value: true
clip_coef:
    value: 0.2
clip_vfloss:
    value: true
critic_act_fn:
    value: tanh
critic_layers:
    value:
        - 512
        - 256
        - 256
critic_lr:
    value: 0.00025
cuda:
    value: true
difficulty:
    value: 0
entropy_coef:
    value: 0.01
env_config_path:
    value: scenario.json
env_id:
    value: bus14
exp_tag:
    value: my_
gae_lambda:
    value: 0.95
gamma:
    value: 0.9
max_grad_norm:
    value: 10
n_envs:
    value: 1
n_minibatches:
    value: 4
n_steps:
    value: 20000
n_threads:
    value: 1
norm_adv:
    value: true
norm_obs:
    value: true
resume_run_name:
    value: ""
seed:
    value: 42
target_kl:
    value: null
th_deterministic:
    value: false
time_limit:
    value: 4000
total_timesteps:
    value: 1000000
track:
    value: true
update_epochs:
    value: 40
use_heuristic:
    value: true
verbose:
    value: true
vf_coef:
    value: 0.5
wandb_entity:
    value: ""
wandb_mode:
    value: online
wandb_project:
    value: rl2grid_bugfinder
