[pop]
node_features = ['p', 'q', 'v', 'sub_id', 'theta', 'cooldown']
edge_features = ['p','p_or','p_ex','q_or','q_ex','a_or','a_ex','theta_or','theta_ex','rho','cooldown','status','thermal_limit','timestep_overflow']
agent_selective_learning = false
manager_selective_learning = true
no_action_reward = true
enable_expert = true
generator_storage_only = true
remove_no_action = true
manager_remove_no_action = true
safe_max_rho = 0.99

[agent]
embedding = "egat_architecture_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-2
learning_frequency = 4
target_network_weight_replace_steps = 500
gamma = 0.99
huber_loss_delta = 1.0
batch_size = 4
intrinsic_reward_relevance = 1e-3

[agent.exploration]
method = "episodic_memory"
size = 1000
neighbors = 10
exploration_bonus_limit = 5
maximum_similarity = 8

[agent.exploration.random_network_distiller]
network = "egat_architecture_very_very_small"
learning_rate = 1e-2

[agent.exploration.inverse_model]
embedding = "egat_architecture_very_very_small"
action_prediction_stream = "inverse_action_stream_very_small"
learning_rate = 1e-2

[agent.replay_memory]
alpha = 0.5
max_beta = 1.0
min_beta = 0.0
annihilation_rate = 200
capacity = 1000

[manager]
embedding = "egat_architecture_very_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-2
learning_frequency = 4
target_network_weight_replace_steps = 500
gamma = 0.99
huber_loss_delta = 1.0
batch_size = 4

[manager.exploration]
method = "episodic_memory"
size = 10000
neighbors = 10
exploration_bonus_limit = 5
maximum_similarity = 8

[manager.exploration.random_network_distiller]
network = "egat_architecture_very_very_small"
learning_rate = 1e-2

[manager.exploration.inverse_model]
embedding = "egat_architecture_very_very_small"
action_prediction_stream = "inverse_action_stream_very_small"
learning_rate = 1e-2

[manager.replay_memory]
alpha = 0.5
max_beta = 1.0
min_beta = 0.0
annihilation_rate = 200
capacity = 1000

[head_manager]
embedding = "gat_architecture_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-2
learning_frequency = 4
target_network_weight_replace_steps = 500
gamma = 0.99
huber_loss_delta = 1.0
batch_size = 4

[head_manager.exploration]
method = "episodic_memory"
size = 30000
neighbors = 10
exploration_bonus_limit = 5
maximum_similarity = 8

[head_manager.exploration.random_network_distiller]
network = "gat_architecture_very_small"
learning_rate = 1e-2

[head_manager.exploration.inverse_model]
embedding = "gat_architecture_very_small"
action_prediction_stream = "inverse_action_stream_very_small"
learning_rate = 1e-2

[head_manager.replay_memory]
alpha = 0.5
max_beta = 1.0
min_beta = 0.0
annihilation_rate = 200
capacity = 1000


