[pop]
node_features = ['p', 'q', 'v', 'theta']
edge_features = ['p','p_or','p_ex','q_or','q_ex','a_or','a_ex','theta_or','theta_ex','rho','cooldown','thermal_limit','timestep_overflow']
enable_expert = true
safe_max_rho = 0.99
actions_per_generator = 10
manager_selective_learning = true
generator_storage_only = true
remove_no_action = true
manager_remove_no_action = true

[agent]
embedding = "egat_architecture_very_very_small"
advantage_stream = "advantage_stream_very_small"
value_stream = "value_stream_very_small"
learning_rate = 1e-5
adam_epsilon = 1.5e-4
learning_frequency = 4
target_network_weight_replace_steps = 100
gamma = 0.99
huber_loss_delta = 2
batch_size = 288
intrinsic_reward_relevance = 0.1

[agent.exploration]
method = "episodic_memory"
size = 100
neighbors = 10
exploration_bonus_limit = 5
maximum_similarity = 8

[agent.exploration.random_network_distiller]
network = "egat_architecture_very_very_small"
learning_rate = 1e-5
adam_epsilon=1.5e-4

[agent.exploration.inverse_model]
embedding = "egat_architecture_very_very_small"
action_prediction_stream = "inverse_action_stream_very_small"
learning_rate = 1e-5
adam_epsilon=1.5e-4

[agent.replay_memory]
alpha = 0.7
max_beta = 1.0
min_beta = 0.5
annihilation_rate = 1250
capacity = 500

[manager]
embedding = "egat_architecture_very_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-5
adam_epsilon = 1.5e-4
learning_frequency = 4
target_network_weight_replace_steps = 100
gamma = 0.99
huber_loss_delta = 2
batch_size = 288
intrinsic_reward_relevance = 0.1

[manager.exploration]
method = "episodic_memory"
size = 1000
neighbors = 10
exploration_bonus_limit = 5
maximum_similarity = 8

[manager.exploration.random_network_distiller]
network = "egat_architecture_very_small"
learning_rate = 1e-5
adam_epsilon=1.5e-4

[manager.exploration.inverse_model]
embedding = "egat_architecture_very_small"
action_prediction_stream = "inverse_action_stream_very_small"
learning_rate = 1e-5
adam_epsilon=1.5e-4

[manager.replay_memory]
alpha = 0.7
max_beta = 1.0
min_beta = 0.5
annihilation_rate = 1250
capacity = 5000

[head_manager]
embedding = "gat_architecture_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-5
adam_epsilon = 1.5e-4
learning_frequency = 4
target_network_weight_replace_steps = 100
gamma = 0.99
huber_loss_delta = 2
batch_size = 288
intrinsic_reward_relevance = 0.1

[head_manager.exploration]
method = "episodic_memory"
size = 5000
neighbors = 10
exploration_bonus_limit = 5
maximum_similarity = 8

[head_manager.exploration.random_network_distiller]
network = "gat_architecture_small"
learning_rate = 1e-5
adam_epsilon=1.5e-4

[head_manager.exploration.inverse_model]
embedding = "gat_architecture_small"
action_prediction_stream = "inverse_action_stream_very_small"
learning_rate = 1e-5
adam_epsilon=1.5e-4

[head_manager.replay_memory]
alpha = 0.7
max_beta = 1.0
min_beta = 0.5
annihilation_rate = 1250
capacity = 10000

